spring.application.name=transaction-api

server.port=${SERVER_PORT:8080}

transaction-service.url=${TRANSACTION_SERVICE_URL:http://localhost:8081}

spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.cloud.openfeign.okhttp.enabled=false
spring.cloud.openfeign.httpclient.hc5.enabled=true

security.encryption.key=${AES_SECRET_KEY}

security.jwt.secret=${JWT_SECRET_KEY}
security.jwt.expiration-minutes=10