spring.application.name=transaction-service

server.port=${SERVER_PORT:8081}

spring.datasource.url=jdbc:h2:mem:transactiondb
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always