package com.bethocr.transactionapi.dto.response;

public enum ErrorCode {
    VALIDATION_ERROR,
    MALFORMED_JSON,
    TRANSACTION_NOT_FOUND,
    REFERENCE_GENERATION_ERROR,
    DATA_INTEGRITY_VIOLATION,

    DECRYPTION_ERROR,
    TRANSACTION_SERVICE_ERROR,
    TRANSACTION_SERVICE_UNAVAILABLE,
    INVALID_TRANSACTION_STATUS,
    INVALID_TRANSACTION_SERVICE_RESPONSE,

    INTERNAL_SERVER_ERROR
}